lightx2v/__main__.py, lightx2v/attentions/common/sage_attn2.py, lightx2v/text2v/models/networks/wan/infer/feature_caching/transformer_infer.py, lightx2v/text2v/models/networks/wan/infer/transformer_infer.py, lightx2v/text2v/models/schedulers/wan/feature_caching/scheduler.py, lightx2v/text2v/models/schedulers/wan/scheduler.py
=> Support wan2.1 sageattn and fix oom for 720P.

lightx2v/__main__.py, lightx2v/text2v/models/networks/wan/lora_adapter.py, lightx2v/text2v/models/networks/wan/model.py
=> feat: support LoRA

lightx2v/text2v/models/networks/wan/lora_adapter.py, scripts/run_wan_i2v_with_lora.sh
=> feat: refactor LoRA handling and add run script

lightx2v/__main__.py
=> Support batch test

README.md, configs/wan_t2v_causal.json, lightx2v/__main__.py, lightx2v/attentions/common/sage_attn2.py, lightx2v/models/networks/wan/causal_model.py, lightx2v/models/networks/wan/infer/causal/transformer_infer.py, lightx2v/models/networks/wan/infer/utils.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/wan/wan_causal_runner.py, lightx2v/models/schedulers/wan/causal/scheduler.py, lightx2v/models/schedulers/wan/scheduler.py, scripts/run_wan_t2v_causal.sh
This PR add support for autoregressive inference of wan2.1-t2v
=> support autoregressive inference for wan2.1-t2v

configs/wan_i2v.json, examples/diffusers/converter.py, lightx2v/api_server.py, lightx2v/attentions/distributed/comm/ring_comm.py, lightx2v/attentions/distributed/partial_heads_attn/tests/test_acc.py, lightx2v/common/backend_infer/trt/common.py, lightx2v/common/ops/mm/mm_weight.py, lightx2v/infer.py, lightx2v/models/input_encoders/hf/clip/model.py, lightx2v/models/input_encoders/hf/llama/model.py, lightx2v/models/input_encoders/hf/llava/model.py, lightx2v/models/input_encoders/hf/t5/model.py, lightx2v/models/input_encoders/hf/xlm_roberta/model.py, lightx2v/models/networks/wan/model.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/graph_runner.py, lightx2v/models/runners/wan/wan_causal_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/video_encoders/hf/wan/vae.py, lightx2v/utils/profiler.py, lightx2v/utils/quant_utils.py, lightx2v/utils/utils.py, scripts/post.py
=> Support convert weight to diffusers.

README.md, configs/wan_skyreels_v2_df.json, configs/wan_skyreels_v2_i2v.json, configs/wan_skyreels_v2_t2v.json, lightx2v/attentions/common/sage_attn2.py, lightx2v/infer.py, lightx2v/models/networks/wan/infer/post_infer.py, lightx2v/models/networks/wan/infer/pre_infer.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/wan/wan_skyreels_v2_df_runner.py, lightx2v/models/schedulers/scheduler.py, lightx2v/models/schedulers/wan/df/skyreels_v2_df_scheduler.py, lightx2v/models/schedulers/wan/scheduler.py, scripts/run_wan_skyreels_v2_df.sh, scripts/run_wan_skyreels_v2_i2v.sh, scripts/run_wan_skyreels_v2_t2v.sh
=> Support: SkyReels-V2 AutoRegressive Diffusion-Forcing Inference

lightx2v/models/networks/wan/model.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/wan/wan_runner.py
=> Support load safetensors format quant weights.

scripts/run_wan_t2v_causvid.sh
=> bug fixed for causvid script

configs/advanced_ptq/wan_i2v.json, lightx2v/common/ops/mm/mm_weight.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/networks/wan/model.py, lightx2v/models/networks/wan/weights/transformer_weights.py, scripts/run_wan_i2v_advanced_ptq.sh
=> Support load advance ptq model.

configs/wan_t2v_causvid_save_quant.json, scripts/run_wan_t2v_causvid_save_quant.sh
=> update configs for causvid

lightx2v/models/networks/hunyuan/infer/feature_caching/transformer_infer.py, lightx2v/models/networks/hunyuan/infer/pre_infer.py, lightx2v/models/networks/hunyuan/infer/transformer_infer.py, lightx2v/models/networks/hunyuan/weights/pre_weights.py, lightx2v/models/networks/hunyuan/weights/transformer_weights.py, lightx2v/models/networks/wan/infer/causvid/transformer_infer.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/networks/wan/weights/transformer_weights.py, lightx2v/utils/set_config.py
This PR deprecate attention functions for hunyuan and wan
=> [major]: deprecated attention functions

lightx2v/models/runners/wan/wan_runner.py
=> Fix  bug: wan's target_video_len hard code

lightx2v/api_multi_server.py, scripts/start_multi_server.sh
=> [feature] add server for multi-gpus

configs/wan_i2v_causvid.json, lightx2v/models/networks/wan/causvid_model.py, lightx2v/models/networks/wan/infer/causvid/transformer_infer.py, lightx2v/models/networks/wan/infer/pre_infer.py, lightx2v/models/runners/wan/wan_causvid_runner.py, lightx2v/models/schedulers/wan/causvid/scheduler.py, scripts/run_wan_i2v_causvid.sh
=> [feature]: Add CausalVid I2V

lightx2v/common/ops/mm/mm_weight.py, lightx2v/models/input_encoders/hf/t5/model.py, lightx2v/models/input_encoders/hf/xlm_roberta/model.py, lightx2v/models/networks/wan/lora_adapter.py, lightx2v/models/networks/wan/model.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/video_encoders/hf/wan/vae.py, lightx2v/utils/memory_profiler.py
=> fix offload

configs/offload/wan_i2v_block.json, configs/offload/wan_i2v_phase.json, configs/offload/wan_t2v_block.json, configs/offload/wan_t2v_phase.json, lightx2v/common/modules/weight_module.py, lightx2v/common/offload/manager.py, lightx2v/common/ops/conv/conv3d.py, lightx2v/models/input_encoders/hf/t5/model.py, lightx2v/models/networks/hunyuan/infer/transformer_infer.py, lightx2v/models/networks/wan/infer/causvid/transformer_infer.py, lightx2v/models/networks/wan/infer/pre_infer.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/networks/wan/model.py, lightx2v/models/networks/wan/weights/pre_weights.py, lightx2v/models/networks/wan/weights/transformer_weights.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/video_encoders/hf/tae.py, lightx2v/models/video_encoders/hf/wan/vae.py, lightx2v/models/video_encoders/hf/wan/vae_tiny.py, lightx2v/utils/set_config.py
=> Add support for running lightx2v on 8 GB GPUs

lightx2v/attentions/distributed/comm/all2all.py, lightx2v/common/offload/manager.py, lightx2v/models/input_encoders/hf/t5/model.py, lightx2v/models/input_encoders/hf/xlm_roberta/model.py, lightx2v/models/networks/hunyuan/infer/transformer_infer.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/networks/wan/lora_adapter.py, lightx2v/models/networks/wan/model.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/video_encoders/hf/wan/vae.py, lightx2v/utils/profiler.py
=> async offload & context4debug

configs/deploy/hunyuan_i2v.json, configs/deploy/hunyuan_t2v.json, configs/deploy/wan_i2v.json, configs/deploy/wan_t2v.json, lightx2v/api_server.py, lightx2v/common/apis/image_encoder.py, lightx2v/common/apis/text_encoder.py, lightx2v/common/apis/vae.py, lightx2v/infer.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/hunyuan/hunyuan_runner.py, lightx2v/models/runners/wan/wan_causvid_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/utils/service_utils.py, scripts/deploy/start_image_encoder_server.sh, scripts/deploy/start_server.sh, scripts/deploy/start_text_encoder_server.sh, scripts/deploy/start_vae_server.sh
[feature] support split server
=> [feature] support split server

lightx2v/infer.py
=> async infer.py

README.md
For deepwiki  auto refresh
```shell
```
```shell
```
- Avoid hard-coding local paths: Make sure your submissions do not include hard-coded local paths, as these paths are specific to individual development environments and can cause compatibility issues. Use relative paths or configuration files …
=> For deepwiki auto refresh

docs/en_US/03.quantization.md, docs/zh_CN/03.quantization.md, gradio_demo.py, lightx2v/attentions/distributed/ring/attn.py, lightx2v/common/ops/mm/mm_weight.py, lightx2v/common/ops/norm/rms_norm_weight.py, lightx2v/infer.py, lightx2v/models/networks/wan/infer/utils.py, lightx2v/models/runners/default_runner.py, lightx2v/utils/utils.py, tools/convert/converter.py
=> Support gradio demo for wan i2v.

lightx2v/models/video_encoders/hf/wan/vae.py
=> fix a image cat bug in parallel vae

lightx2v/common/transformer_infer/transformer_infer.py, lightx2v/models/networks/wan/infer/feature_caching/transformer_infer.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/networks/wan/model.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/schedulers/scheduler.py, lightx2v/models/schedulers/wan/feature_caching/scheduler.py, lightx2v/models/schedulers/wan/scheduler.py
=> update feature caching

lightx2v/models/networks/hunyuan/infer/feature_caching/transformer_infer.py, lightx2v/models/networks/hunyuan/model.py, lightx2v/models/networks/wan/infer/feature_caching/transformer_infer.py, lightx2v/models/networks/wan/model.py, lightx2v/models/runners/hunyuan/hunyuan_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/schedulers/hunyuan/feature_caching/scheduler.py, lightx2v/models/schedulers/hunyuan/scheduler.py
=> update hunyuan cache

.gitignore, lightx2v_kernel/CMakeLists.txt, lightx2v_kernel/csrc/common_extension.cc, lightx2v_kernel/csrc/gemm/mxfp8_quant_kernels_sm120.cu, lightx2v_kernel/csrc/gemm/mxfp8_scaled_mm_kernels_sm120.cu, lightx2v_kernel/include/lightx2v_kernel_ops.h, lightx2v_kernel/python/lightx2v_kernel/gemm.py, lightx2v_kernel/python/lightx2v_kernel/utils.py, lightx2v_kernel/test/mxfp8_mxfp8/test_bench.py, lightx2v_kernel/test/mxfp8_mxfp8/test_mm_tflops.py, lightx2v_kernel/test/mxfp8_mxfp8/test_mxfp8_quant.py, lightx2v_kernel/test/mxfp8_mxfp8/test_quant_mem_utils.py
=> add mxfp8 quant kernel and some tests

app/gradio_demo.py, app/gradio_demo_zh.py, lightx2v/common/ops/attn/attn_weight.py
=> Fix torch sdpa op

docs/ZH_CN/source/method_tutorials/cache.md
=> upload videos for cache README

docs/EN/source/deploy_guides/lora_deploy.md, docs/ZH_CN/source/deploy_guides/lora_deploy.md, lightx2v/api_server.py, lightx2v/infer.py, lightx2v/models/runners/base_runner.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/wan/wan_audio_runner.py, lightx2v/models/runners/wan/wan_causvid_runner.py, lightx2v/models/runners/wan/wan_distill_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/server/service.py, lightx2v/utils/set_config.py
=> Enhance BaseRunner with model protocols and type hints and fix lora load

docs/EN/source/deploy_guides/deploy_local_windows.md, docs/ZH_CN/source/deploy_guides/deploy_local_windows.md, requirements_win.txt
=> Add windows docs

lightx2v_kernel/csrc/gemm/mxfp6_mxfp8_scaled_mm_kernels_sm120.cu, lightx2v_kernel/csrc/gemm/mxfp8_scaled_mm_kernels_sm120.cu, lightx2v_kernel/csrc/gemm/nvfp4_scaled_mm_kernels_sm120.cu, lightx2v_kernel/test/mxfp6_mxfp8/test_bench3_bias.py, lightx2v_kernel/test/mxfp6_mxfp8/test_mxfp6_quant.py, lightx2v_kernel/test/mxfp8_mxfp8/test_bench3_bias.py, lightx2v_kernel/test/mxfp8_mxfp8/test_mxfp8_quant.py
=> fix bias epilogue

lightx2v_kernel/CMakeLists.txt, lightx2v_kernel/csrc/common_extension.cc, lightx2v_kernel/csrc/gemm/mxfp4_quant_kernels_sm120.cu, lightx2v_kernel/csrc/gemm/mxfp4_scaled_mm_kernels_sm120.cu, lightx2v_kernel/csrc/gemm/mxfp6_quant_kernels_sm120.cu, lightx2v_kernel/csrc/gemm/nvfp4_quant_kernels_sm120.cu, lightx2v_kernel/include/lightx2v_kernel_ops.h, lightx2v_kernel/python/lightx2v_kernel/gemm.py, lightx2v_kernel/test/mxfp4_mxfp4/test_bench.py, lightx2v_kernel/test/mxfp4_mxfp4/test_bench3_bias.py, lightx2v_kernel/test/mxfp4_mxfp4/test_mxfp4_quant.py, lightx2v_kernel/test/mxfp6_mxfp8/test_bench.py, lightx2v_kernel/test/mxfp6_mxfp8/test_bench3_bias.py, lightx2v_kernel/test/mxfp6_mxfp8/test_mxfp6_quant.py, lightx2v_kernel/test/mxfp6_mxfp8/test_quant_mem_utils.py, lightx2v_kernel/test/mxfp8_mxfp8/test_quant_mem_utils.py, lightx2v_kernel/test/nvfp4_nvfp4/test_bench1.py, lightx2v_kernel/test/nvfp4_nvfp4/test_bench2.py, lightx2v_kernel/test/nvfp4_nvfp4/test_bench3_bias.py, lightx2v_kernel/test/nvfp4_nvfp4/test_mm_tflops.py, lightx2v_kernel/test/nvfp4_nvfp4/test_quant_mem_utils.py
=> add mxfp4 kernels and rename some func for clarity

app/gradio_demo.py, app/gradio_demo_zh.py, app/run_gradio.sh
=> Remove unused paths

docs/EN/source/deploy_guides/deploy_local_windows.md, docs/ZH_CN/source/deploy_guides/deploy_local_windows.md, lightx2v/common/ops/attn/flash_attn.py, lightx2v/common/ops/attn/ring_attn.py, lightx2v/common/ops/attn/sage_attn.py
=> Fix logger bug

configs/wan22/wan_ti2v_i2v.json, configs/wan22/wan_ti2v_t2v.json, lightx2v/common/apis/vae.py, lightx2v/infer.py, lightx2v/models/networks/wan/infer/audio/pre_wan_audio_infer.py, lightx2v/models/networks/wan/infer/post_infer.py, lightx2v/models/networks/wan/infer/pre_infer.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/runners/base_runner.py, lightx2v/models/runners/cogvideox/cogvidex_runner.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/hunyuan/hunyuan_runner.py, lightx2v/models/runners/wan/wan_audio_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/runners/wan/wan_skyreels_v2_df_runner.py, lightx2v/models/schedulers/wan/scheduler.py, lightx2v/models/video_encoders/hf/wan/vae_2_2.py, lightx2v/utils/utils.py, scripts/wan22/run_wan22_i2v.sh, scripts/wan22/run_wan22_t2v.sh
=> Support wan2.2 ti2v-5B and fix some bugs.

configs/caching/teacache/wan_ti2v_tea_720p.json
=> Add tea cache for wan2.2-5B

lightx2v/models/input_encoders/hf/t5/model.py, lightx2v/models/input_encoders/hf/xlm_roberta/model.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/networks/wan/model.py, lightx2v/models/runners/wan/wan_audio_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/video_encoders/hf/wan/vae.py, lightx2v/models/video_encoders/hf/wan/vae_2_2.py, lightx2v/utils/utils.py
=> Fix load weights bug.

lightx2v/api_server.py, lightx2v/server/README.md, lightx2v/server/api.py, lightx2v/server/config.py, lightx2v/server/distributed_utils.py, lightx2v/server/gpu_manager.py, lightx2v/server/image_utils.py, lightx2v/server/main.py, lightx2v/server/schema.py, lightx2v/server/service.py, lightx2v/server/task_manager.py, lightx2v/server/utils.py, scripts/server/post_i2v.py, scripts/server/post_multi_servers.py, scripts/server/post_multi_servers_i2v.py, scripts/server/start_server.sh
- Introduced `image_utils.py` with functions to check, extract, and save base64-encoded images.
- Updated `TaskRequest` schema to accept base64 images or URLs in `image_path`.
- Modified `VideoGenerationService` to handle base64 images, saving them appropriately.
- Updated scripts to convert local image paths to base64 before sending requests.
```shell
```
```shell
```
3. Finally, please double-check your code to ensure it …
=> refactor: server api

lightx2v/models/networks/wan/infer/audio/post_wan_audio_infer.py, lightx2v/models/networks/wan/infer/post_infer.py, lightx2v/models/networks/wan/infer/transformer_infer.py, lightx2v/models/networks/wan/model.py, lightx2v/models/networks/wan/weights/transformer_weights.py
=> Fix offload bug in new dist infer

lightx2v/models/runners/wan/wan_audio_runner.py
=> Fix: Audio vae/clip input dim dismatch

configs/qwen_image/qwen_image_i2i.json, lightx2v/infer.py, lightx2v/models/input_encoders/hf/qwen25/qwen25_vlforconditionalgeneration.py, lightx2v/models/networks/qwen_image/infer/pre_infer.py, lightx2v/models/networks/qwen_image/model.py, lightx2v/models/runners/qwen_image/qwen_image_runner.py, lightx2v/models/schedulers/qwen_image/scheduler.py, lightx2v/models/video_encoders/hf/qwen_image/vae.py, scripts/qwen_image/qwen_image_i2i.sh
=> feature: support qwen-image-edit(i2i)

lightx2v/common/ops/attn/ulysses_attn.py, lightx2v/models/networks/wan/infer/transformer_infer.py
=> [Fix] Fix sage-attn distribute bug

configs/audio_driven/wan_i2v_audio_quant.json, lightx2v/models/input_encoders/hf/q_linear.py, lightx2v/models/input_encoders/hf/seko_audio/audio_adapter.py, lightx2v/models/input_encoders/hf/seko_audio/audio_encoder.py, lightx2v/models/networks/wan/audio_model.py, lightx2v/models/networks/wan/infer/audio/post_infer.py, lightx2v/models/networks/wan/infer/audio/pre_infer.py, lightx2v/models/networks/wan/infer/audio/transformer_infer.py, lightx2v/models/networks/wan/infer/module_io.py, lightx2v/models/networks/wan/infer/vace/transformer_infer.py, lightx2v/models/runners/base_runner.py, lightx2v/models/runners/default_runner.py, lightx2v/models/runners/wan/wan_audio_runner.py, lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/schedulers/wan/audio/scheduler.py, lightx2v/models/schedulers/wan/changing_resolution/scheduler.py, lightx2v/models/schedulers/wan/scheduler.py, tools/convert/quant_adapter.py
=> Refactor runners

lightx2v/models/networks/wan/infer/module_io.py, lightx2v/models/runners/wan/wan_vace_runner.py, scripts/wan/run_wan_vace.sh
=> [Fix] fix vace bug

lightx2v/models/runners/wan/wan_audio_runner.py
=> fix: video stitching flicker/shrink issue

configs/seko_talk/seko_talk_11_fp8_dist_fixed_shape.json, lightx2v/models/runners/wan/wan_audio_runner.py, lightx2v/models/schedulers/wan/audio/scheduler.py, scripts/seko_talk/run_seko_talk_11_fp8_dist_fixed_shape.sh
=> Support fixed_shape resize for seko & update scheduler for seko

lightx2v/models/runners/wan/wan_runner.py, lightx2v/models/video_encoders/hf/wan/vae_tiny.py
=> [feat] support lightvae

lightx2v/models/runners/wan/wan_audio_runner.py, lightx2v/models/schedulers/wan/audio/scheduler.py, lightx2v/models/video_encoders/hf/wan/vae.py
=> Support vae 2d-grid dist infer & Rewrite  FramePreprocessor using torch
